version: "3.7"
services:
  pwa:
    build: 
      context: .
      dockerfile: Dockerfile_dev
    environment:
      API_URL: "${API_URL}"
    ports:
      - "3000:3000"
    restart: on-failure
    volumes:
      - .:/app