<template>
  <!-- the only one component generated by quasar itself, good to learn the basics about components -->
  <q-item v-if="!isDisabled" clickable tag="a" :href="link">
    <q-item-section v-if="icon" avatar>
      <q-icon :name="icon" />
    </q-item-section>

    <q-item-section>
      <q-item-label>{{ title }}</q-item-label>
      <q-item-label caption>{{ caption }}</q-item-label>
    </q-item-section>
  </q-item>
</template>

<script setup>
const props = defineProps({
  title: {
    type: String,
    required: true,
  },

  onlyDev: Boolean,

  caption: {
    type: String,
    default: '',
  },

  link: {
    type: String,
    default: '#',
  },

  icon: {
    type: String,
    default: '',
  },
});
const { title, onlyDev, caption, link, icon } = toRefs(props);

const isDisabled = computed(() => {
  if (!process.env.DEV) return onlyDev;
  else return false;
});
</script>
