# docker-compose to build the image and set up a mariadb database
version: "3.7"
services:
  mariadb:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "studicar"
      MYSQL_USER: "studicar"
      MYSQL_PASSWORD: "@H1xhm978zX?v67g"
    restart: always
    volumes:
      - ./mariadb:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      - mariadb
  api:
    build: .
    ports:
      - "443:443"
    restart: always
    environment:
      DB_HOST: "mariadb"
      DB_DATABASE: "studicar"
      DB_USER: "studicar"
      DB_PASSWORD: "@H1xhm978zX?v67g"
      USE_HTTPS: "true"
      MAIL_HOST: "${MAIL_HOST}"
      MAIL_PORT: "${MAIL_PORT}"
      MAIL_USER: "${MAIL_USER}"
      MAIL_PASS: "${MAIL_PASS}"
      FIREBASE_TYPE: "${FIREBASE_TYPE}"
      FIREBASE_PROJECT_ID: "${FIREBASE_PROJECT_ID}"
      FIREBASE_PRIVATE_KEY_ID: "${FIREBASE_PRIVATE_KEY_ID}"
      FIREBASE_PRIVATE_KEY: "${FIREBASE_PRIVATE_KEY}"
      FIREBASE_CLIENT_EMAIL: "${FIREBASE_CLIENT_EMAIL}"
      FIREBASE_CLIENT_ID: "${FIREBASE_CLIENT_ID}"
      FIREBASE_AUTH_URI: "${FIREBASE_AUTH_URI}"
      FIREBASE_TOKEN_URI: "${FIREBASE_TOKEN_URI}"
      FIREBASE_AUTH_PROVIDER_X509_CERT_URL: "${FIREBASE_AUTH_PROVIDER_X509_CERT_URL}"
      FIREBASE_CLIENT_X509_CERT_URL: "${FIREBASE_CLIENT_X509_CERT_URL}"
    # for accessing other database on localhost 
    # giving docker access to the local network is necessary.
    # Uncomment the following line to enable.
    #network_mode: "host"
    depends_on:
      - mariadb
    command: ["npm", "run", "nodemon"]
    volumes:
      - .:/app