name: Build and publish to mfinn.de

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pwa:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm install -g @quasar/cli
    - run: npm install -g @quasar/icongenie
    - run: cd ./pwa && npm ci
    - run: cd ./pwa && npm run build
    - uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ftp://mfinn.de/httpdocs/studicar/dev/pwa
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./pwa/dist/pwa
  api:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ftp://mfinn.de/httpdocs/studicar/dev/api
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./api
