name: Build and publish to mfinn.de

on:
  push:
    branches: [master]

jobs:
  pwa:
    runs-on: ubuntu-latest

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Build dockerfile and push image to Docker Hub and Github Registry
        uses: docker/build-push-action@v2
        with:
          context: ./pwa
          push: true
          tags: |
            ghcr.io/f1nnm/studicar_pwa:${{ github.run_number }}
            ghcr.io/f1nnm/studicar_pwa:latest
      -
        name: Print tag
        run: echo "Tagged images with latest and $GITHUB_RUN_NUMBER"
  api:
    runs-on: ubuntu-latest

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Build dockerfile and push image to Docker Hub and Github Registry
        uses: docker/build-push-action@v2
        with:
          context: ./api
          push: true
          tags: |
            ghcr.io/f1nnm/studicar_api:${{ github.run_number }}
            ghcr.io/f1nnm/studicar_api:latest
      -
        name: Print tag
        run: echo "Tagged images with latest and $GITHUB_RUN_NUMBER"
