# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and publish to mfinn.de

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm install -g @quasar/cli
    - run: quasar ext add @quasar/icon-genie
    - run: npm ci
    - run: npm run build
    - uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ftp://mfinn.de/httpdocs/studicar/dev/pwa
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./pwa/dist/pwa
    - uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ftp://mfinn.de/httpdocs/studicar/dev/api
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./api
