name: Publish releases to live website

on:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm install -g @quasar/cli
    - run: quasar ext add @quasar/icon-genie
    - run: npm ci
    - run: npm run build
    - uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ftp://mfinn.de/httpdocs/studicar/live/pwa
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./pwa/dist/pwa
    - uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ftp://mfinn.de/httpdocs/studicar/live/api
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./api
