name: Publish releases to live website

on:
  release:
    types: [released]
jobs:
  pwa:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm install -g @quasar/cli
    - run: npm install -g @quasar/icongenie
    - run: cd ./pwa && npm ci
    - run: cd ./pwa && npm run build
    - uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: mfinn.de
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./pwa/dist/pwa/
        server-dir: /live/pwa/
  api:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: cd ./api && npm ci && mkdir tmp && date > ./tmp/restart.txt
    - uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: mfinn.de
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./api/
        server-dir: /live/api/
        exclude: .git* .git*/**
