module.exports = [
  "Leider muss ich ihnen mitteilen, dass ich Ihre Absage auf meine Bewerbung nicht akzeptieren kann. Ich fange nächste Woche an. Viel Erfolg beim nächsten Mal!",
  '"Ich studiere dual." - "Haben Sie mich gerade Aal genannt?!"',
  "Meine Mathe-Kenntnisse: Addition, Subtraktion, Frustration, Aufgebentraktion",
  "Der Duale Student: Eine perfekte Mischung aus jung und erfahren - findet man sonst nur auf dem Straßenstrich.",
  "Bei meinem Dualen Studium habe ich ganz neue Hobbys entdeckt: ich überweise jetzt Geld an meine Freunde und beleidige sie im Verwendungszweck",
  "Rosen sind rot, Uni verpennt, Geld kommt trotzdem - Dualer Student",
  "Da schreibe ich ein halbes Jahr mit ihm und plötzlich kommt nichts mehr. Irgendwelche Tipps, oder soll ich mir direkt einen neuen Kuli kaufen?",
  "Was haben der Duale Student und Kohlensäure gemeinsam? Sie steigen beide aus der Limo.",
  "Ich sorge für eine hohe Durchfallquote - Manfred, 55, Mensakoch",
  "\"Was macht die Uni?\" - \"Nichts macht die Uni, ich muss alles selber machen ...",
  'Die schönsten Worte sind nicht "Ich liebe dich" sondern "nicht klausurrelevant"',
  "Der Unterschied zwischen Theorie und Praxis ist Vergleichbar mit Einkaufszettel und Kassenbon",
  "Du bist Student, wenn es dich beruhigt, dass dein Freund auch noch nicht angefangen hat zu lernen. 2 Tage vor der Klausur",
  "Der Duale Student trinkt seinen Kaffee schwarz - ohne Wasser.",
  "Du bist Student, wenn du so lange ein Motivationsproblem hast, bis du ein Zeitproblem hast.",
  "Der Duale Student feiert auch seinen Geburtstag dual: er feiert rein und wieder raus.",
  "Das Duale Studium ist die Happy Hour unter den Karriereoptionen. Es gibt 2 für 1, man steht unter Zeitdruck, aber am Ende ist man den anderen immer einen Schritt voraus.",
  "Du bist Student, wenn deine Aufmerksamkeit von einem Moment auf den anderen von 0 auf 100 steigt, wenn das Wort „klausurrelevant“ fällt.",
  "Ein normaler Student spielt Tischtennis auf seinem iPad. Der Duale Student spielt Tischtennis mit seinem iPad.",
  "Lerntipp: mache eine Pause, stehe auf, strecke dich. Gehe spazieren, fahre zum Flughafen und steige in ein Flugzeug. Komme nie wieder.",
  "Der Duale Student verpackt seine Valentinstagsgrüße in eine PowerPoint- Präsentation.",
  "Ein Kontoauszug ist ja auch nur eine visuelle Aufzeigung fragwürdiger Entscheidungen.",
  "Der Duale Student liest keine Zeitungen. Er sorgt selbst für Schlagzeilen.",
  'Der Duale Student - das "F" steht für Freizeit',
  "Baby bitte mach' dir nie mehr Sorgen um Geld! Gib' mir nur deine Hand, ich bin dualer Student",
  "Der Duale Student hat keine Zeit für das Freibad, er lernt lieber am eigenen Pool.",
  "Der Duale Student verabredet sich nicht. Er vereinbart Meetings.",
  "Vier Studenten im kaputten Auto: Maschinenbauer: Zündkerzen kaputt! Elektrotechniker: Batterie leer! Chemiker: Benzin verunreinigt! Informatiker: Wir sollten aus- und wieder einsteigen.",
  'Der normale Student: "Kopf oder Zahl" - Der Duale Student: "Chip oder Magnetstreifen?"',
  "Wenn du dual studierst tanzt du nicht, du hast dann Geld für Alkohol.",
  "Der Duale Student liest keine Bücher. Er least einen Mercedes.",
  'Der Duale Student sortiert nach "Preis absteigend"',
  "Gerade hat mich ein Ersti gefragt, ob ich ihm einen 50€ Schein klein machen kann. Ich musste lachen, der ist doch schon klein!",
  "Dating Tipp für Informatiker: versuche einfach mal was zu sagen. Dating Tipp für BWLer: halt am Besten den Mund.",
  "“Wie ist denn das Wetter bei euch?” - “Ganz schön Caps Lock, es Shift ohne Ende!”",
  "Du bist Student, wenn du eine 10 Minuten Lernpause einlegst, auf die Uhr schaust, und vier Stunden vergangen sind.",
  "Ein normaler Student: „Endlich Semesterferien.“ - Der Duale Student: „Endlich wieder Uni.“",
  "Wenn der Duale Student bei der Bahn einsteigt, dann als Aktionär.",
  "Der Duale Student liest keine Fachbücher, er korrigiert sie.",
  "Der Duale Student feiert keine Partys. Er feiert sich selbst!",
  "Der Duale Student braucht keinen Schlaf - er hat Geld für Kaffee.",
  "Du bist Student, wenn du dir nicht sicher bist, ob du Freizeit oder einfach etwas vergessen hast.",
  "Der Duale Student macht sich nichts aus Geld, außer Papierflieger.",
  "Mit seinen Dozenten zu diskutieren ist wie die AGB zu lesen. Am Ende ignoriert man alles und stimmt einfach zu.",
  "Hashtags waren gestern. Der Duale Student nutzt Cashtags.",
  "Der Duale Student hat zwar einen Studierendenausweis, zahlt aber trotzdem immer den vollen Preis. $WeilErEsKann.",
  "„Du siehst gut aus, so glücklich. Bist du verliebt?“ „Nö, ich trinke jetzt auch unter Woche.“",
  "Der duale Student schafft 70 Sekunden in einer Minute.",
  "Der duale Student wäscht nicht, er kauft sich einfach neue Sachen.",
  "Wenn der Duale Student Sonne braucht, wechselt er sein Hintergrundbild.",
  "Der Duale Student hat keinen Urlaub, er baut Überstunden ab.",
];
